cmake_minimum_required(VERSION 3.20)
project(sps_scan C CXX)
find_package(MLIR REQUIRED CONFIG)
list(APPEND CMAKE_MODULE_PATH "${MLIR_CMAKE_DIR}" "${LLVM_CMAKE_DIR}")
include(AddLLVM)
include(AddMLIR)
include(HandleLLVMOptions)
include_directories(${LLVM_INCLUDE_DIRS} ${MLIR_INCLUDE_DIRS})
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(sps-scan src/sps-scan.cpp)
target_link_libraries(sps-scan PRIVATE
  MLIRAnalysis MLIRDLTIDialect MLIRLLVMDialect MLIRParser MLIRIR MLIRSupport)
llvm_update_compile_flags(sps-scan)
